FROM alpine

RUN apk update && \
	apk add vim

#https://takacsmark.com/dockerfile-tutorial-by-example-dockerfile-best-practices-2018/#1-create-the-dockerfile

#docker build -t ex00 .
#docker run --rm -ti ex00 /bin/sh
#vim --v
